# Generated by Django 5.1.1 on 2024-09-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='branch',
            field=models.CharField(choices=[('CSE Core', 'CSE Core'), ('CSE+Spec', 'CSE+Spec'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil'), ('Biotechnology', 'Biotechnology'), ('Any', 'Any')], max_length=50),
        ),
        migrations.AlterField(
            model_name='session',
            name='purpose',
            field=models.CharField(choices=[('Academics', 'Academics'), ('CodeSesh', 'CodeSesh'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='session',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
