# Generated by Django 5.1.1 on 2024-09-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_session_is_active_alter_session_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='branch',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='purpose',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
