# Generated by Django 5.1.1 on 2024-09-22 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_session_branch_alter_session_purpose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='enrollment_year',
            field=models.IntegerField(default=2020),
            preserve_default=False,
        ),
    ]
