# Generated by Django 5.1.1 on 2024-09-21 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_session_branch_alter_session_purpose_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='is_active',
        ),
    ]
