# Generated by Django 5.1.1 on 2024-09-22 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_profile_bio_profile_enrollment_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='enrollment_year',
        ),
    ]
