# Generated by Django 5.1.1 on 2024-09-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_message_text_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='branch',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='registration_number',
            field=models.CharField(default=' ', max_length=9),
            preserve_default=False,
        ),
    ]
