# Generated by Django 5.1.1 on 2024-09-21 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_friendship_unique_together_friendship_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
