# Generated by Django 5.1.1 on 2024-09-21 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_delete_friendship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
