# Generated by Django 5.1.1 on 2024-09-21 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_delete_friendrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
    ]
